# Generated by Django 5.0.6 on 2024-06-06 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bron_time_start', models.DateTimeField()),
                ('bron_time_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brons', to='stadions.stadion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_time', models.DateTimeField()),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='stadions.stadion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
